apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-deployment
  namespace: assessment-krn 
  labels:
    app: node-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: assessment-krn
        image: roor007/assessment-krn-node:latest
        ports:
        - containerPort: 80
        resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 250m
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
