apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  namespace: assessment-krn 
spec:
  selector:
    app: node-app
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
